api_hostname : https://api.cloudpassage.com
port: 443
newserver_group: newservers
log_destination: C:\Cloudpassage Halo\Logs\clean.log
key_pairs:
  AWS:
    key_id:
    secret_key:
  Azure:
    key_id:
    secret_key:
